name: scania_challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - imbalanced-learn
  - scikit-learn
  - xgboost
  - jupyterlab
  - ipykernel
  - nb_conda_kernels
  - pip:
      - streamlit
